clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  check-app-compatbility:
    image: nextcloudci/php5.6:php5.6-3
    environment:
      - APP_NAME=limit_login_to_ip
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Code checker
      - ./occ app:check-code $APP_NAME -c strong-comparison
      - ./occ app:check-code $APP_NAME -c deprecation
      - cd apps/$APP_NAME/
    when:
      matrix:
        TESTS: check-app-compatbility
  check-app-compatbility-stable12:
    image: nextcloudci/php5.6:php5.6-3
    environment:
      - APP_NAME=limit_login_to_ip
      - CORE_BRANCH=stable12
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Code checker
      - ./occ app:check-code $APP_NAME -c strong-comparison
      - ./occ app:check-code $APP_NAME -c deprecation
      - cd apps/$APP_NAME/
    when:
      matrix:
        TESTS: check-app-compatbility-stable12
  signed-off-check:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=limit_login_to_ip
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php ./build/signed-off-checker.php
    when:
      matrix:
        TESTS: signed-off-check
  integration-tests:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=limit_login_to_ip
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php occ app:enable limit_login_to_ip
      - php -S 127.0.0.1:8080 &
      - cd apps/limit_login_to_ip/tests/integration/ && vendor/bin/behat
    when:
      matrix:
        TESTS: integration-tests
  integration-tests-stable12:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=limit_login_to_ip
      - CORE_BRANCH=stable12
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php occ app:enable limit_login_to_ip
      - php -S 127.0.0.1:8080 &
      - cd apps/limit_login_to_ip/tests/integration/ && vendor/bin/behat
    when:
      matrix:
        TESTS: integration-tests-stable12
  integration-tests-stable11:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=limit_login_to_ip
      - CORE_BRANCH=stable11
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php occ app:enable limit_login_to_ip
      - php -S 127.0.0.1:8080 &
      - cd apps/limit_login_to_ip/tests/integration/ && vendor/bin/behat
    when:
      matrix:
        TESTS: integration-tests-stable11

matrix:
  include:
    - TESTS: check-app-compatbility
    - TESTS: check-app-compatbility-stable12
    - TESTS: signed-off-check
    - TESTS: integration-tests
    - TESTS: integration-tests-stable11
    - TESTS: integration-tests-stable12
